### ISSUE TITLE
Issue during installation of HACS addon

### ISSUE THREAD

**Issue by lucientergal** [littleyoda/ha-sma-semp#1]
Hello, owner of SMA inverter and searching solutions to optimize my consumption, i am very interested by your addon!
Unfortunately i cannot install your module on my instance of HAOS:
just after dowload of the module in HACS, i recieved this error message: "The configuration stream could not be loaded: {"message":"Invalid handler specified"}""
I use HAOS on a proxmox VM installed by the following and usefull scripts: https://tteck.github.io/Proxmox/ maybe this specifity can be the reason of this bug?

**Comment by lucientergal** [comment]
Yes! Well done guy, many thanks for your quick answer!
From now, i am able to create integration, with their entities in HA and retrieve that in sunny portal:
![image](https://github.com/user-attachments/assets/b3b818aa-5ed0-4f44-8e73-a11cf7aa1b16)
![image](https://github.com/user-attachments/assets/88c79289-9dc6-485a-93c0-bf660be0186a)
After few minutes, load is automaticaly created:
![image](https://github.com/user-attachments/assets/1c29a142-b80e-48ba-9254-adfdf5edcc35)

I have a question: In order to commute any loads through SHM logic and algorithms ([including their weather forecast](https://www.sunnyportal.com/Templates/Help.aspx?help-context=HoMan_Prognose&lang=en-US)), do you think it can be possible to create an entities in home assistant who received on/off status from SHM (according load parameters created in sunny portal)? For the time being it seems not possible, i cannot assigned anything from HA:
![image](https://github.com/user-attachments/assets/cf8cca69-dd18-4d5e-9f21-13bca61f5b0b)
if it is possible, we can create a "dummy" load in SHM, assigned HA entity:
![image](https://github.com/user-attachments/assets/1f40fe04-0390-415b-9bb2-7cac6b3614ab)
After, ratio grid/PV can be defined and other details:
![image](https://github.com/user-attachments/assets/d8338607-b404-4a9f-b1b5-53940829f56e)
In this setup, we could beneficiate of SMA algorithms,  and easily integrate and manually command these loads on SMA smartphone app if needed:
![Screenshot_2024-10-23-12-49-42-48_15331015e48d76115a19d34f36144d19](https://github.com/user-attachments/assets/96c9e78f-58ef-41c5-b69b-879b6e606f3a)

In any case, many thanks for your job, don't hesitate to tell if i can help (feedback on specific aspect, tutorial or other)

**Comment by littleyoda** [comment]
I'm not 100% sure if I understand you correctly.
I don't understand why you need a HA entity. 

SEMP devices work differently than normal devices in Sunny Portal.
The entire control is done via the dialogue of my integration in Home Assistant. These devices are controlled via the min/max time, consumption and time window for the calendar.
And the SHM then controls the device via the on/off switch. 
If you need more control, you can also use a helper (input boolean). You can then react to a change in the checkbox status via home assistant actions.

Even though I wrote this integration, I have to say that I find it very difficult to map the SHM control options via SEMP. Everyone has to check whether SEMP and so my integraction meets their requirements.

I used the integration primarily to report consumption in Sunny Portal.

**Comment by lucientergal** [comment]
Your integration is efficient to report consumption in sunny portal, no doubt on that.

My idea is to use sunny portal and SHM automation to pilot a switch and use HA just as interface between SMA devices and loads not natively compatible ;-)
